config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'logins/index'
  get 'contacts/new_contact'
  get 'contacts/:id/read', to: 'contacts#read'
  get 'contact_books/:id/index', to: 'contact_books#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'logins#index'

  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :contact

  :chassis
  :make
  :model
  :year
  :trim
  :color
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :contact_book
  has_many :cars

  validates :name, presence: true
  :phone_number
  :instagram
  :address
  :note
end

app/models/contact_book.rb
class ContactBook < ApplicationRecord
  belongs_to :user
  has_many :contacts
  has_many :cars, through: :contacts

  def self.create_for_user(user)
    ContactBook.create(user: user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :contact_book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  def create
  end

  def read
  end

  def update
  end

  def delete
  end
end

app/controllers/contact_books_controller.rb
class ContactBooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @name = current_user.email
    contactbook = current_user.contact_book || ContactBook.create_for_user(current_user)
    contacts = contactbook.contacts
    @names_and_cars = []
    @names_to_ids = {}
    contacts.each do |contact|
      @names_to_ids[contact.name] = contact.id
      contact_cars = []
      if contact.cars.present?
        contact_cars = contact.cars.map {|car| [car.make]}
      end
     @names_and_cars.push([contact.name, contact_cars])
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  def new
    @contact = Contact.new
  end
  def new_contact
  end

  def create
    c = params["[cars]"]
    p = params.extract!(:name, :instagram, :phone_number, :address, :note)
    p.permit!
    @contact = Contact.new(p)
    @contact.contact_book_id = current_user.contact_book.id
    contact_status = @contact.save
    c.permit!
    ap c
    @car = Car.new(c)
    @car.contact_id = @contact.id
    ap @car

    if contact_status && @car.save
      redirect_to(controller: :contact_books, action: 'index', id: current_user.id)
    else
      redirect_to contacts_new_contact_path
    end


  end

  def read
    @contact = Contact.where(id: params[:id], contact_book_id: current_user.contact_book.id).take
    unless @contact.present?
      render :missing_contact
    end
  end

  def update
  end

  def delete
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
    if user_signed_in?
      redirect_to(controller: :contact_books, action: 'index', id: current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/contact_books_helper.rb
module ContactBooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/delete.html.erb
<h1>Cars#delete</h1>
<p>Find me in app/views/cars/delete.html.erb</p>

app/views/cars/read.html.erb
<h1>Cars#read</h1>
<p>Find me in app/views/cars/read.html.erb</p>

app/views/cars/update.html.erb
<h1>Cars#update</h1>
<p>Find me in app/views/cars/update.html.erb</p>

app/views/contact_books/index.html.erb
<h1>Car Contacts - <%= @name %></h1>
<% if @names_and_cars.any? %>
<table>
  <thead>
  <tr>
    <th>Contact</th>
    <th>Current Car</th>
  </tr>
  </thead>
  <tbody>
  <% @names_and_cars.each do |pair| %>
    <tr>
      <td>
        <%= link_to(pair.first, {controller: 'contacts', action: 'read', id: @names_to_ids[pair.first]}) %>
      </td>
      <td><%= pair.last %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>
<br />
<br />
<%= link_to('Add New Contact', contacts_new_contact_path) %>
<br />
<br />
<% if user_signed_in? %>
  <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %>
<% end %>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/delete.html.erb
<h1>Contacts#delete</h1>
<p>Find me in app/views/contacts/delete.html.erb</p>

app/views/contacts/missing_contact.html.erb
<h1>Contact Not Found or You Don't Have Permission</h1>

app/views/contacts/new_contact.html.erb
<%= form_with(model: @contact, url: contacts_path, local: true) do |form| %>
  <div class="field">
    Name
    <%= form.text_field(:name) %>
  </div>
  <div class="field" id='phone_number'>
    Phone Number
    <%= form.text_field(:phone_number) %>
  </div>
  <div class="field">
    Instagram
    <%= form.text_field(:instagram) %>
  </div>
  <div class="field">
    Address
    <%= form.text_field(:address) %>
  </div>
  <div class="field">
    Notes
    <%= form.text_area :note, rows: 4 %>
  </div>

  <%= form.fields_for :cars do |car_fields| %>
    <%= car_fields.label :make %>
    <%= car_fields.text_field :make %>

    <%= car_fields.label :model %>
    <%= car_fields.text_field :model %>

    <%= car_fields.label :year %>
    <%= car_fields.text_field :year %>

    <%= car_fields.label :trim %>
    <%= car_fields.text_field :trim %>

    <%= car_fields.label :color %>
    <%= car_fields.text_field :color %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/read.html.erb
<h1><%= @contact.name %></h1>
<p>Instagram: <%= @contact.instagram %> </p>
<p>Phone Number: <%= @contact.phone_number %> </p>
<p>Address: <%= @contact.address %> </p>
<p>Notes: <%= @contact.note %> </p>

<% if @contact.cars.present? %>
  <h2> Cars </h2>
  <% @contact.cars.each do |car| %>
    <p> <%= car.make %>  </p>
  <% end %>
<% end %>

app/views/contacts/update.html.erb
<h1>Contacts#update</h1>
<p>Find me in app/views/contacts/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarContacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/index.html.erb
<h1>Welcome to Car Contacts</h1>
<%= link_to 'Sign in', new_user_session_path %>

app/views/logins/read.html.erb
<h1>Logins#read</h1>
<p>Find me in app/views/logins/read.html.erb</p>